apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
data:
  dragent.yaml: |
    ### Agent tags
     tags: cluster:vikram-k8,env:test

    # Sysdig collector address
     collector: a222362b14ef411e897dd0a4573f7292-42766350.us-east-1.elb.amazonaws.com

     #Collector TCP port
     collector_port: 6443

     #Whether collector accepts ssl
     ssl: true

    # collector certificate validation
     ssl_verify_certificate: false
     
     dev_new_k8s: true
    
     app_checks:
       - name: elasticsearch1
         check_module: elastic
         pattern:
           port: 9200
           comm: java
         conf:
           url: "http://100.96.1.15:9200"
       
       - name: elasticsearch2
         check_module: elastic
         pattern:
           port: 9200
           comm: java
         conf:
           url: "http://100.96.2.7:9200"
